### ISSUE TITLE
update 37671 corrupted

### ISSUE THREAD

**Issue by matheusstaffa** [HamletDuFromage/switch-cheats-db#1]
The latest update (37671) crashes the atmosphere as soon the switch tries to extract the zip file. I've tried to open the zip file on pc and is only 22 bytes and there is nothing on it. i attached crash log. Please, can you uploud the fixed file?
[01605143859_0100000000000012.log](https://github.com/HamletDuFromage/switch-cheats-db/files/5531651/01605143859_0100000000000012.log)

**Comment by HamletDuFromage** [comment]
yup you're right, don't know what happened. It's fixed now, sorry for the inconvenience. And thank you for letting me know
