### ISSUE TITLE
[Suggestion] Content clarification

### ISSUE THREAD

**Issue by BA0123** [HamletDuFromage/switch-cheats-db#6]
Hi,

This is not an technical issue, but having many similar downloads is a bit confusing. I hope that a clarification is added to the main page so people can tell the difference and know what to download.

Thank you

**Comment by HamletDuFromage** [comment]
This really isn't meant to be used as is, but rather through software like aio switch updater

Are you talking about the releases?

**Comment by BA0123** [comment]
Yeah, I meant the releases. Technically, I get what you're saying, but sometimes I prefer the direct approach by extracting the cheats directly to the SD card.

It's more convenient this way for people with poor connections, or with no connection on their Switch at all.

**Comment by HamletDuFromage** [comment]
That's fair, I'll try to add something in the readme if I can remember 

Basically contents* is for atmosphere, titles* is for sxos (or old ams) but I might depreciate them. contents.zip are the gameplay related cheats, contents_60fps-gfx are the graphics cheats and contents_complete is both combined

**Comment by BA0123** [comment]
That's very helpful, thank you.

Just a side note regarding sxos, I stopped using it years ago since its support stopped, leaving it several major firmwares behind Atmosphere. Unless people object, I'd suggest saving yourself some time and effort and drop sxos support, assuming that most users abandoned it just like me.

You can close this issue if you want. Keep up the great work
